### ISSUE TITLE
如何解决每段语音长度不一的问题

### ISSUE THREAD

**Issue by ANYMS-A** [haoxiangsnr/SNR-Based-Progressive-Learning-of-Deep-Neural-Network-for-Speech-Enhancement#2]
您好，我最近也在做Speech Enhancement相关的课题。由于每段语音的长度不同，导致了它的spectrogram的维度不同，我只能将Batch Size设置为1训练，效率非常低下，请问有什么好的解决方案嘛？

**Comment by haoxiangsnr** [comment]
并没有什么特别优雅的解决方案，GPU矩阵运算要求每个 batch 内的样本尺寸相同（除了 batch size 这个维度），但并不要求不同 batch 内的数据样本尺寸相同。

假设使用 LSTM 或者其他对于输入长度不敏感的模型：

- 按照一个 batch 内最长的语音进行 pad，使一个 batch 内的所有语音长度固定，再进行 STFT
- 或者先做 STFT，之后对一个 batch 内的语音频谱按照同样思路在时间维度上 pad

上面其实是一个思路。注意计算损失的时候，仅仅计算原始有效部分的损失，不要把 pad 出的内容算进去。

**Comment by haoxiangsnr** [comment]
DataLoader for various length of data：https://discuss.pytorch.org/t/dataloader-for-various-length-of-data/6418/13

**Comment by ANYMS-A** [comment]
对对，就是GPU批处理需要batch内尺寸相同的问题，谢谢你的建议！我现在用了个比较繁琐的办法：把语音切割成相同大小的size，最后合成的时候再拼接。
